import xml.etree.ElementTree as ET

tree = ET.parse('gradle/verification-metadata.xml')
root = tree.getroot()
components = root.find('components')

def add_component(group, name, version, artifact_name, sha256):
    comp = ET.SubElement(components, 'component', {'group': group, 'name': name, 'version': version})
    art = ET.SubElement(comp, 'artifact', {'name': artifact_name})
    sha = ET.SubElement(art, 'sha256', {'value': sha256, 'origin': 'Generated by Gradle'})

add_component('com.android.library', 'com.android.library.gradle.plugin', '8.10.1', 'com.android.library.gradle.plugin-8.10.1.pom', '15ef43979515ae24d4807c26ef9b050869d6c7bce3063c044e5188bb590ae07e')

ET.indent(tree, space="   ", level=0)
tree.write('gradle/verification-metadata.xml', encoding='utf-8', xml_declaration=True)
